#!/bin/bash

set -e

cd "$(dirname "$0")/../builtinFonts"

echo "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh"
echo "#pragma once"
echo ""

echo "#define BOOKERLY_S_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./bookerly_s_regular.h",
  "./bookerly_s_bold.h",
  "./bookerly_s_bolditalic.h",
  "./bookerly_s_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define BOOKERLY_M_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./bookerly_m_regular.h",
  "./bookerly_m_bold.h",
  "./bookerly_m_bolditalic.h",
  "./bookerly_m_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define BOOKERLY_L_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./bookerly_l_regular.h",
  "./bookerly_l_bold.h",
  "./bookerly_l_bolditalic.h",
  "./bookerly_l_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define BOOKERLY_XL_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./bookerly_xl_regular.h",
  "./bookerly_xl_bold.h",
  "./bookerly_xl_bolditalic.h",
  "./bookerly_xl_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_10_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./ubuntu_10_regular.h",
  "./ubuntu_10_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./ubuntu_12_regular.h",
  "./ubuntu_12_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define SMALL_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosans_8_regular.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"
