#pragma once

#include <builtinFonts/bookerly_18_bold.h>
#include <builtinFonts/bookerly_18_bolditalic.h>
#include <builtinFonts/bookerly_18_italic.h>
#include <builtinFonts/bookerly_18_regular.h>
#include <builtinFonts/bookerly_20_bold.h>
#include <builtinFonts/bookerly_20_bolditalic.h>
#include <builtinFonts/bookerly_20_italic.h>
#include <builtinFonts/bookerly_20_regular.h>
#include <builtinFonts/bookerly_22_bold.h>
#include <builtinFonts/bookerly_22_bolditalic.h>
#include <builtinFonts/bookerly_22_italic.h>
#include <builtinFonts/bookerly_22_regular.h>
#include <builtinFonts/bookerly_24_bold.h>
#include <builtinFonts/bookerly_24_bolditalic.h>
#include <builtinFonts/bookerly_24_italic.h>
#include <builtinFonts/bookerly_24_regular.h>
#include <builtinFonts/notosans_8_regular.h>
#include <builtinFonts/ubuntu_10_bold.h>
#include <builtinFonts/ubuntu_10_regular.h>
#include <builtinFonts/ubuntu_12_bold.h>
#include <builtinFonts/ubuntu_12_regular.h>
