#pragma once

#include <builtinFonts/bookerly_s_bold.h>
#include <builtinFonts/bookerly_s_bolditalic.h>
#include <builtinFonts/bookerly_s_italic.h>
#include <builtinFonts/bookerly_s_regular.h>
#include <builtinFonts/bookerly_m_bold.h>
#include <builtinFonts/bookerly_m_bolditalic.h>
#include <builtinFonts/bookerly_m_italic.h>
#include <builtinFonts/bookerly_m_regular.h>
#include <builtinFonts/bookerly_l_bold.h>
#include <builtinFonts/bookerly_l_bolditalic.h>
#include <builtinFonts/bookerly_l_italic.h>
#include <builtinFonts/bookerly_l_regular.h>
#include <builtinFonts/bookerly_xl_bold.h>
#include <builtinFonts/bookerly_xl_bolditalic.h>
#include <builtinFonts/bookerly_xl_italic.h>
#include <builtinFonts/bookerly_xl_regular.h>
#include <builtinFonts/notosans_8_regular.h>
#include <builtinFonts/ubuntu_10_bold.h>
#include <builtinFonts/ubuntu_10_regular.h>
#include <builtinFonts/ubuntu_12_bold.h>
#include <builtinFonts/ubuntu_12_regular.h>
