// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define BOOKERLY_S_FONT_ID (685938368)
#define BOOKERLY_M_FONT_ID (-1378439322)
#define BOOKERLY_L_FONT_ID (230443583)
#define BOOKERLY_XL_FONT_ID (1580902064)
#define UI_10_FONT_ID (1851133737)
#define UI_12_FONT_ID (1001447213)
#define SMALL_FONT_ID (188290029)
