// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define BOOKERLY_18_FONT_ID (180586357)
#define BOOKERLY_20_FONT_ID (-1414909999)
#define BOOKERLY_22_FONT_ID (-798236650)
#define BOOKERLY_24_FONT_ID (998007044)
#define UI_10_FONT_ID (1851133737)
#define UI_12_FONT_ID (1001447213)
#define SMALL_FONT_ID (188290029)
